### ISSUE TITLE
Report extra `Task` param in embedded pipelines

### ISSUE THREAD

**Issue by madbence** [IBM/tekton-lint#43]
https://github.com/IBM/tekton-lint/blob/7218c6b6a08c032394584d5849e29528b51d73ab/regression-tests/no-extra-param.yaml#L51-L56

It should be reported by the `no-extra-param` rule.

**Comment by tonymaynard** [comment]
I removed the extra params and I believe you already have reporting in place for this or am I misunderstanding? Is this scenario not covered by this line (https://github.com/IBM/tekton-lint/blob/7218c6b6a08c032394584d5849e29528b51d73ab/src/rules/no-extra-param.ts#L20) I attached a screenshot which shows the diff in the snapshot when I removed the extra params. 
<img width="928" alt="Screenshot 2020-10-28 at 09 24 10" src="https://user-images.githubusercontent.com/43777547/97417538-b8bc3000-18ff-11eb-88b8-7119c8bd1f70.png">

**Comment by madbence** [comment]
@tonymaynard i don't think so. the code you mentioned iterates over pipeline definitions (`tekton.pipelines`), but the mentioned code has those extra params inside on of the defintions in `resourcetemplates` of a `TriggerTemplate` (`tekton.triggertemplates`), so I think it should be fixed somewhere here: https://github.com/IBM/tekton-lint/blob/7218c6b6a08c032394584d5849e29528b51d73ab/src/rules/no-extra-param.ts#L52-L62

As you can see, the code only checks `PipelineRun`s which have `pipelineRef` (as opposed to `pipelineSpec`).

**Comment by mbwhite** [comment]
resolved in pr #42
